exotik/accounts/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views

from .forms import LoginForm

from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
	path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html', redirect_authenticated_user=True, authentication_form=LoginForm), name='login'),
	path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html', next_page='accounts:login'), name='logout'),
]

exotik/activities/urls.py
from unicodedata import name
from django.urls import path

from . import views

app_name = 'activities'

urlpatterns = [
    path('random/', views.random, name='random'),
    path('random_api/', views.random_api),
]

exotik/exotik/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('activities/', include('activities.urls')),
    path('accounts/', include('accounts.urls')),
    path('todos/', include('todos.urls')),
    path('facts/', include('facts.urls')),
]

exotik/facts/urls.py
from django.urls import path

from . import views

app_name = 'facts'

urlpatterns = [
    path('', views.index, name='index')
]

exotik/todos/urls.py
from django.urls import path

from . import views

app_name = 'todos'

urlpatterns = [
    path('', views.index, name='index'),
    path('old_todo/<str:date>/', views.old_todo, name='old_todo'),
    path('add_todo/', views.add_todo, name='add_todo'),
    path('remove_task/<int:id>/', views.remove_task, name='remove_task'),
    path('done_task/<int:id>/', views.done_task, name='done_task'),
    path('calendar/', views.calendar, name='calendar'),
    path('random_calendar/', views.random_calendar, name='random_calendar'),
]

exotik/templates/layouts/partials/footer.html
<footer class="footer">
    <div class="container">
        <div>
            <p>© {% now "Y" %} Built with &#10084;&#65039; by Fady's Cube</p>
            <a href="https://github.com/fadyscube/exotik" target="_blank" class="link-social">
                <svg width="24" height="24" fill="none" viewBox="0 0 24 24">
                    <path fill="#fff" d="M12.001 0C5.371-.003 0 5.511 0 12.317c0 5.381 3.36 9.956 8.038 11.636.63.163.534-.297.534-.611v-2.135c-3.638.438-3.786-2.035-4.03-2.448-.493-.865-1.66-1.085-1.311-1.498.828-.438 1.673.11 2.652 1.594.708 1.077 2.088.895 2.788.716.153-.647.48-1.225.93-1.674-3.77-.694-5.34-3.057-5.34-5.867 0-1.363.437-2.616 1.295-3.627-.547-1.666.05-3.093.131-3.305 1.558-.143 3.177 1.146 3.303 1.248.885-.245 1.896-.375 3.027-.375 1.137 0 2.15.135 3.044.383.303-.237 1.804-1.344 3.252-1.21.078.213.662 1.607.148 3.25.868 1.014 1.31 2.278 1.31 3.645 0 2.814-1.581 5.18-5.362 5.863.324.327.581.717.756 1.148.176.43.266.892.266 1.358v3.099c.021.248 0 .493.402.493C20.58 22.356 24 17.748 24 12.32 24 5.51 18.627 0 12.001 0z"></path>
                </svg>
            </a>
        </div>
    </div>
</footer>

exotik/templates/layouts/partials/header.html
{% load static %}

<header class="header">
    <div class="container">
        <a href="{% url 'index' %}"><h2 style="color: #958bff;">Exotik</h2></a>
        <div class="menu">
            <nav>
                <div class="menu-link">
                    <a href="{% url 'activities:random' %}">
                        <button>
                            Random activities
                        </button>
                    </a>
                </div>
                <div class="menu-link">
                    <a href="{% url 'todos:index' %}">
                        <button>
                            Todo list
                        </button>
                    </a>
                </div>
                <div class="menu-link">
                    <a href="{% url 'todos:calendar' %}">
                        <button>
                            Calendar
                        </button>
                    </a>
                </div>
                <div class="menu-link">
                    <a href="{% url 'facts:index' %}">
                        <button>
                            Facts
                        </button>
                    </a>
                </div>
            </nav>
            <div class="menu-buttons">
                {% if request.user.is_authenticated %}
                    <a href="{% url 'accounts:logout' %}" class="btn-outline">Logout ({{ request.user.username }})</a>
                {% else %}
                    <a href="{% url 'accounts:login' %}" class="btn-outline menu-login">Login</a>
                    <a href="{% url 'accounts:register' %}" class="btn menu-register">Sign up</a>
                {% endif %}
            </div>
        </div>
    </div>
</header>