exotik/exotik/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('activities/', include('activities.urls')),
    path('accounts/', include('accounts.urls')),
    path('todos/', include('todos.urls')),
    path('facts/', include('facts.urls')),
]

exotik/facts/urls.py
from django.urls import path

from . import views

app_name = 'facts'

urlpatterns = [
    path('', views.index, name='index')
]

exotik/todos/urls.py
from django.urls import path

from . import views

app_name = 'todos'

urlpatterns = [
    path('', views.index, name='index'),
    path('old_todo/<str:date>/', views.old_todo, name='old_todo'),
    path('add_todo/', views.add_todo, name='add_todo'),
    path('remove_task/<int:id>/', views.remove_task, name='remove_task'),
    path('done_task/<int:id>/', views.done_task, name='done_task'),
    path('calendar/', views.calendar, name='calendar'),
    path('random_calendar/', views.random_calendar, name='random_calendar'),
]

exotik/todos/models.py
from django.db import models

from datetime import datetime

from django.contrib.auth.models import User

# Create your models here.

class Task(models.Model):
    title = models.CharField(max_length=255)
    done = models.BooleanField(default=False)
    date = models.CharField(max_length=10, default=str(datetime.date(datetime.now())))
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_random = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    @classmethod
    def get_dates(self, user):
        dates = []
        for i in self.objects.filter(user=user):
            if i.date not in dates:
                dates.append(i.date)

        return dates

exotik/todos/forms.py
from django import urls

from django.forms import ModelForm

from .models import Task


class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'is_random']

exotik/todos/views.py
from django.shortcuts import redirect, render

from .forms import TaskForm

from .models import Task

from activities.models import Activity

import datetime

from django.http import Http404, HttpResponseRedirect

from django.contrib.auth.decorators import login_required

import random as rd

# Create your views here.

@login_required
def index(request):
    tasks = Task.objects.filter(date=str(datetime.datetime.date(datetime.datetime.now())), user=request.user).order_by('id')

    context = {
        'tasks': tasks,
    }
    return render(request, 'todos/index.html', context)


@login_required
def add_todo(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)

        if form.is_valid():
            form = form.save(commit=False)
            form.user = request.user
            form.save()

            return redirect('todos:index')

        else:
            form = TaskForm()


@login_required
def remove_task(request, id):
    task = Task.objects.get(id=id)

    if task.user == request.user:
        task.delete()
        return HttpResponseRedirect(request.GET['next'])


@login_required
def calendar(request):
    tasks = Task.objects.filter(user=request.user).order_by('id')
    data = {}

    days = [str(datetime.date.today() + datetime.timedelta(days=i)) for i in range(0 - datetime.date.today().weekday(), 7 - datetime.date.today().weekday())]

    for i in days:
        data[i] = []

    for date in Task.get_dates(user=request.user):
        for task in tasks:
            if task.date == date and task.date in days:
                if len(data[date]) < 7:
                    data[date].append(task)
        
    context = {
        'data': data,
        'today': str(datetime.date.today()),

    }
    return render(request, 'todos/calendar.html', context)


@login_required
def old_todo(request, date):
    tasks = Task.objects.filter(date=date, user=request.user).order_by('id')
    if datetime.datetime.strptime(date, '%Y-%m-%d').date() < datetime.date.today():
        context = {
            'tasks': tasks,
            'date': date,
        }
        return render(request, 'todos/old_todo.html', context)

    else:
        if request.method == 'POST':
            form = TaskForm(request.POST)

            if form.is_valid():
                form = form.save(commit=False)
                form.user = request.user
                form.date = date
                form.save()

                return redirect('todos:old_todo', date)

        else:
            form = TaskForm()

        context = {
            'form': form,
            'date': date,
            'tasks': tasks,
        }
        return render(request, 'todos/future_todo.html', context)


@login_required
def done_task(request, id):
    task = Task.objects.get(id=id)

    if task.user == request.user:
        if task.done == False:
            task.done  = True
        else:
            task.done = False
        task.save()
        return HttpResponseRedirect(request.GET['next'])
    else:
        return Http404


@login_required
def random_calendar(request):
    activities = []
    for i in Activity.objects.all():
        activities.append({
            'id': i.id,
            'activity': i.activity,
            'type': i._type,
        })

    days = [str(datetime.date.today() + datetime.timedelta(days=i)) for i in range(0 - datetime.date.today().weekday(), 7 - datetime.date.today().weekday())]
    for date in days:
        if date >= str(datetime.date.today()):
            Task.objects.create(title=rd.choice(activities)['activity'], user=request.user, date=date, is_random=True)

    return redirect('todos:calendar')

exotik/todos/templates/todos/calendar.html
{% extends 'layouts/base.html' %}

{% load static %}
{% load str_to_date %}

{% block title %}Calendar{% endblock title %}

{% block css %}
<link rel="stylesheet" href="{% static 'todos/css/styles.css' %}">
{% endblock css %}

{% block body %}
<div class="main">
    <div class="calendar">
        <h2 class="todos-heading text-white">Calendar</h2>
        <div class="random-calendar">
            <a class="btn random" href="{% url 'todos:random_calendar' %}">Generate random calendar <i class="fa-solid fa-wand-magic-sparkles"></i></a>
        </div>
        <div class="clearfix">
            {% for date, tasks in data.items %}
                <div class="date">
                    <div class="card">
                        {% if date == today %}
                            <a href="{% url 'todos:old_todo' date %}"><h3 style="color: #cb87f6;" class="date-title">{{ date|str_to_date }}</h3></a>
                            <svg width="300" height="8" fill="none" viewBox="0 0 300 8">
                                <path fill="#cb87f6" d="M0 0h293.991L300 4l-6.009 4H0l6.39-4L0 0z"></path>
                            </svg>
                        {% else %}
                            <a href="{% url 'todos:old_todo' date %}"><h3 class="date-title">{{ date|str_to_date }}</h3></a>
                            <svg width="300" height="8" fill="none" viewBox="0 0 300 8">
                                <path fill="#a097f2" d="M0 0h293.991L300 4l-6.009 4H0l6.39-4L0 0z"></path>
                            </svg>
                        {% endif %}
                        <div class="date-tasks">
                            {% for task in tasks %}
                                {% if task.is_random %}
                                    {% if task.done %}
                                        <div class="date-task is-random">
                                            <strike>{{ task|truncatechars:24 }}</strike>
                                        </div>
                                    {% else %}
                                        <div class="date-task is-random">
                                            {{ task|truncatechars:24 }}
                                        </div>
                                    {% endif %}
                                {% else %}
                                    {% if task.done %}
                                        <div class="date-task">
                                            <strike>{{ task|truncatechars:24 }}</strike>
                                        </div>
                                    {% else %}
                                        <div class="date-task">
                                            {{ task|truncatechars:24 }}
                                        </div>
                                    {% endif %}
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock body %}


{% block js %}
<script src="{% static 'todos/js/app.js' %}"></script>
{% endblock js %}

exotik/todos/templates/todos/future_todo.html
{% extends 'layouts/base.html' %}

{% load static %}
{% load str_to_date %}

{% block title %}Todo list{% endblock title %}

{% block css %}
<link rel="stylesheet" href="{% static 'todos/css/styles.css' %}">
{% endblock css %}

{% block body %}
<div class="main">
    <div class="todos">
        <form action="{% url 'todos:old_todo' date %}" method="post">
            {% csrf_token %}
            <h2 class="todos-heading">Todo list of {{ date|str_to_date }}</h2>
            
            <div class="todo-input-parent">
                <input class="todo-input" type="text" id="title" name="title" placeholder="New Todo">
                <button id="submit" type="submit" class="btn add-todo"><i class="fa-solid fa-plus"></i></button>
            </div>
    
            <div class="tasks">
                <div class="tasks">
                    {% for task in tasks %}
                        <div class="task">
                            {% if task.done == False %}
                                <p class="task-name" type="text"><a href="{% url 'todos:done_task' task.id %}?next={{ request.path }}">{{ task }}</a></p>
                            {% else %}
                                <p class="task-name" type="text"><a href="{% url 'todos:done_task' task.id %}?next={{ request.path }}"><strike>{{ task }}</strike></a></p>
                            {% endif %}
                            <a href="{% url 'todos:remove_task' task.id %}?next={{ request.path }}" id="{{ task.id }}" class="task-remove"><i class="fa-solid fa-xmark"></i></a>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </form>
    </div>
</div>
<div id="csrf_token" style="display: none;">{{ csrf_token }}</div>
{% endblock body %}


{% block js %}
<script src="{% static 'todos/js/app.js' %}"></script>
{% endblock js %}

exotik/todos/templates/todos/index.html
{% extends 'layouts/base.html' %}

{% load static %}

{% block title %}Todo list{% endblock title %}

{% block css %}
<link rel="stylesheet" href="{% static 'todos/css/styles.css' %}">
{% endblock css %}

{% block body %}
<div class="main">
    <div class="todos">
        <form action="{% url 'todos:add_todo' %}" method="post">
            {% csrf_token %}
            <h2 class="todos-heading">Todo list of today</h2>
            
            <div class="todo-input-parent">
                <input class="todo-input" type="text" id="title" name="title" placeholder="New Todo">
                <button id="submit" type="submit" class="btn add-todo"><i class="fa-solid fa-plus"></i></button>
            </div>
    
            <div class="tasks">
                <div class="tasks">
                    {% for task in tasks %}
                        <div class="task">
                            {% if task.done == False %}
                                <p class="task-name" type="text"><a href="{% url 'todos:done_task' task.id %}?next={{ request.path }}">{{ task }}</a></p>
                            {% else %}
                                <p class="task-name" type="text"><a href="{% url 'todos:done_task' task.id %}?next={{ request.path }}"><strike>{{ task }}</strike></a></p>
                            {% endif %}
                            <a href="{% url 'todos:remove_task' task.id %}?next={{ request.path }}" id="{{ task.id }}" class="task-remove"><i class="fa-solid fa-xmark"></i></a>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock body %}


{% block js %}
<script src="{% static 'todos/js/app.js' %}"></script>
{% endblock js %}

exotik/todos/templates/todos/old_todo.html
{% extends 'layouts/base.html' %}

{% load static %}
{% load str_to_date %}

{% block title %}Todo list{% endblock title %}

{% block css %}
<link rel="stylesheet" href="{% static 'todos/css/styles.css' %}">
{% endblock css %}

{% block body %}
<div class="main">
    <div class="todos">
        {% csrf_token %}
        <h2 class="todos-heading">Todo list of {{ date|str_to_date }}</h2>

        <div class="tasks">
            <div class="tasks">
                {% for task in tasks %}
                    <div class="task">
                        {% if task.done == False %}
                            <p class="task-name" type="text"><a href="{% url 'todos:done_task' task.id %}?next={{ request.path }}">{{ task }}</a></p>
                        {% else %}
                            <p class="task-name" type="text"><a href="{% url 'todos:done_task' task.id %}?next={{ request.path }}"><strike>{{ task }}</strike></a></p>
                        {% endif %}
                        <a href="{% url 'todos:remove_task' task.id %}?next={{ request.path }}" id="{{ task.id }}" class="task-remove"><i class="fa-solid fa-xmark"></i></a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
<div id="csrf_token" style="display: none;">{{ csrf_token }}</div>
{% endblock body %}


{% block js %}
<script src="{% static 'todos/js/app.js' %}"></script>
{% endblock js %}